### ISSUE TITLE
trgen throws System.NullReferenceException working with OpenQASM 3 grammar

### ISSUE THREAD

**Issue by jwoehr** [kaby76/Domemtech.Trash#164]
Apologies for complete newbie question ... working towards a .vsix for the [OpenQASM 3 language](https://github.com/openqasm/openqasm).

```
git clone https://github.com/openqasm/openqasm
cd openqasm/source/grammar
trgen
Rendering template file from CSharp/CaseChangingCharStream.cs to Generated/CaseChangingCharStream.cs
System.NullReferenceException: Object reference not set to an instance of an object.
   at Trash.Command.Cap(String str) in C:\Users\Kenne\Documents\GitHub\Domemtech.Trash\trgen\Command.cs:line 1310
   at Trash.Command.GenFromTemplates(Command p, PerGrammar per_grammar) in C:\Users\Kenne\Documents\GitHub\Domemtech.Trash\trgen\Command.cs:line 1169
   at Trash.Command.GenerateSingle(PerGrammar per_grammar) in C:\Users\Kenne\Documents\GitHub\Domemtech.Trash\trgen\Command.cs:line 1020
   at Trash.Command.Doit(PerGrammar per_grammar, HashSet`1 merged_list) in C:\Users\Kenne\Documents\GitHub\Domemtech.Trash\trgen\Command.cs:line 993
   at Trash.Command.DoNonMavenGenerate(PerGrammar per_grammar) in C:\Users\Kenne\Documents\GitHub\Domemtech.Trash\trgen\Command.cs:line 1362
   at Trash.Command.Execute(Config co) in C:\Users\Kenne\Documents\GitHub\Domemtech.Trash\trgen\Command.cs:line 46
   at Trash.Program.MainInternal(String[] args) in C:\Users\Kenne\Documents\GitHub\Domemtech.Trash\trgen\Program.cs:line 85
   at Trash.Program.Main(String[] args) in C:\Users\Kenne\Documents\GitHub\Domemtech.Trash\trgen\Program.cs:line 21
```
Greatly appreciate your help on this!

**Comment by kaby76** [comment]
I haven't added yet code to find the EOF-start rule. For now, try "trgen -s program" instead of just "trgen". Sorry.

**Comment by jwoehr** [comment]
Thanks @kaby76 ... my mistake .. I had tried `trgen program` and forgotten the `-s`.
`trgen -s program` worked.
