### ISSUE TITLE
trparse -- antlr3.dll missing on Linux

### ISSUE THREAD

**Issue by philip-h-dye** [kaby76/Domemtech.Trash#253]
On Ubuntu 20.04:

$ trparse gUnit.g3
System.IO.FileNotFoundException: Could not load file or assembly '/home/phdyex/.dotnet/tools/.store/trparse/0.20.12/trparse/0.20.12/tools/net7.0/any/antlr3.dll'. The system cannot find the file specified.
File name: '/home/phdyex/.dotnet/tools/.store/trparse/0.20.12/trparse/0.20.12/tools/net7.0/any/antlr3.dll'
   at System.Reflection.Assembly.LoadFile(String path)
   at Trash.Grun.DoParse(String parser_type, String txt, String prefix, String input_name, Int32 row_number, List`1 data) in C:\Users\Kenne\Documents\GitHub\Domemtech.Trash\src\trparse\Grun.cs:line 189
   at Trash.Grun.Run(String parser_type) in C:\Users\Kenne\Documents\GitHub\Domemtech.Trash\src\trparse\Grun.cs:line 123

Please advise.  Thanks

**Comment by nkakouros** [comment]
This issue still persist. With the main branch I get:

```
System.IO.FileNotFoundException: Could not load file or assembly '/home/nikos/projects/grammar/Domemtech.Trash/bin/Debug/net7.0/Antlr4.Runtime.Standard.dll'. The system cannot find the file specified.
File name: '/home/nikos/projects/grammar/Domemtech.Trash/bin/Debug/net7.0/Antlr4.Runtime.Standard.dll'
   at System.Reflection.Assembly.LoadFile(String path)
   at Trash.Grun.DoParse(String parser_type, String txt, String prefix, String input_name, Int32 row_number, List`1 data) in C:\Users\Kenne\Documents\GitHub\Domemtech.Trash\src\trparse\Grun.cs:line 202
   at Trash.Grun.Run(String parser_type) in C:\Users\Kenne\Documents\GitHub\Domemtech.Trash\src\trparse\Grun.cs:line 144
```

I managed to download and place Antlr4.Runtime.Standard.dll to the expected place, but then I get Test.dll missing.

**Comment by kaby76** [comment]
There were a few hardwired references to paths with "Debug". These are being corrected. The tools are published in "Release" configuration, which is now the default when typing "make" at the root directory of the cloned repo.

Make sure you don't have multiple .dotnet directories, and the ~/.dotnet/tools/tr* tools are removed and the ~/.dotnet/tools/.store/tr* files are also removed. Best, again, to use the [uninstall commands](https://github.com/kaby76/Domemtech.Trash#uninstall) from the command line Bash shell, then run the [install commands](https://github.com/kaby76/Domemtech.Trash#install).

For now, you can work around the problem by setting the type of the parse: `trparse -t ANTLRv3 foobar.whateversuffix`. The problem is that when it does not know the extension, trparse wants to parse the file using a parser that has been generated and built using CSharp as the target, which involves the path "Generated-CSharp/". If there's no code built code, it fails to do the parse.

The normal procedure for using the tools is to perform "trgen" with a .g4 in the current directory. That creates a Generated-CSharp/ directory with a driver for parsing. Then, building that, trparse will default to using the generated parser.

**Comment by nkakouros** [comment]
Thank you for the instructions. I moved past the error into a new one. Forgive me if I am clueless, but this what I do:

- First clone the repo anew 
- switch to the dev branch
- run the install commands from the README (I have uninstalled everything first)
- Then, I run `trparse -t ebnf my-grammar.ebnf`. 
```

But I get this error:

```
System.Exception: Unknown file extension, cannot load in a built-in parser.
   at Trash.Grun.DoParse(String parser_type, String txt, String prefix, String input_name, Int32 row_number, List`1 data) in C:\Users\Kenne\Documents\GitHub\Domemtech.Trash\src\trparse\Grun.cs:line 220
   at Trash.Grun.Run(String parser_type) in C:\Users\Kenne\Documents\GitHub\Domemtech.Trash\src\trparse\Grun.cs:line 144
```

This means I think that I need to generate sth to pass to trparse via the `-p` flag. I read on trparse help:

```
-p, --parser     Location of pre-built parser (aka the trgen Generated/
    directory)
```

So, I suspect I need to use `trgen` to generate sth. But now I am lost. Why is the built-in parser not found? How can I create it?

If it helps, my use case is that I want to convert a ebnf grammar to antrl4.

**Comment by kaby76** [comment]
All parsers to trparse are bootstrapped parsers from trgen. trparse does not interpret the grammar. A program--which is a simple parser from a template--needs to be generated and compiled first. You can then execute the program itself, or use trparse as part of a chain of commands that pass parse trees via stdin and stdout.

For some grammars, I added as a convenience some grammars to the tool and make an association of the file name extension with the type of grammar. That helps so you don't need to clone grammars-v4 and generate a parser for that grammar (like ANTLRv4). Most of the time, you need to generate a parser driver program that trparse can then use. Other than a very simple and small table of extensions do I associate with a grammar. To avoid all of that code that tests the file name, just read from stdin.

There is no "ebnf" grammar yet. The closest EBNF grammar, which is pretty simple and not very good, is [here](https://github.com/antlr/grammars-v4/tree/master/bnf).

This is how you would build a parser for the grammar, and use trparse.
```
git clone https://github.com/antlr/grammars-v4.git
cd grammars-v4/bnf
trgen -t CSharp
cd Generated-CSharp
dotnet build Test.csproj
cat ../examples/postal.bnf | trparse | trtext
cat ../examples/postal.bnf | trparse | trtree
trparse ../examples/postal.bnf | trtext
trparse ../examples/postal.bnf | trtree
cat ../examples/postal.bnf | ./bin/Debug/net7.0/Test
cat ../examples/postal.bnf | ./bin/Debug/net7.0/Test -tree -tokens
./bin/Debug/net7.0/Test ../examples/postal.bnf

```
